#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_buffer_reference : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "common.inc"
#include "descriptor_layout.inc"
#include "push_constants.inc"
#include "probes.inc.glsl"

void main() {

}
