#pragma once
#include <type_traits>
#include <concepts>
#include <vulkan/vulkan.h>

// clang-format off

#ifdef ENG_DEBUG_BUILD
#include <eng/common/logger.hpp>
#define VK_CHECK(func)                                                                                                 \
    if(const auto res = func; res != VK_SUCCESS) { ENG_ERROR("{}", #func); }
#else
#define VK_CHECK(func) func
#endif



namespace eng
{
namespace gfx
{
namespace vk
{
template<typename T> requires(std::is_standard_layout_v<T>()) T init() { return T{}; }
template<typename T, VkStructureType sType> T init() requires(std::is_standard_layout_v<T>()) { T t{}; t.sType = sType; return t; }

#define INIT_VK_STRUCT(type) struct type : public ::type            \
{                                                                   \
    type() : ::type() {}                                            \
}
#define INIT_VK_STRUCT_S(type, stype) struct type : public ::type   \
{                                                                   \
    type() : ::type() { this->sType = stype; }                      \
};

INIT_VK_STRUCT(VkBufferImageCopy);
INIT_VK_STRUCT(VkAccelerationStructureBuildRangeInfoKHR);
INIT_VK_STRUCT(VkImageCopy);
INIT_VK_STRUCT(VkAccelerationStructureInstanceKHR);
INIT_VK_STRUCT(VkStridedDeviceAddressRegionKHR);
INIT_VK_STRUCT(VkDescriptorBufferInfo);
INIT_VK_STRUCT(VkDescriptorImageInfo);
INIT_VK_STRUCT(VkBufferCopy);
INIT_VK_STRUCT(VkDescriptorSetLayoutBinding);

INIT_VK_STRUCT_S(VkWin32SurfaceCreateInfoKHR, VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR);
INIT_VK_STRUCT_S(VkPhysicalDeviceSynchronization2Features, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceHostQueryResetFeatures, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_QUERY_RESET_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceDynamicRenderingFeatures, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceDescriptorIndexingFeatures, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceFeatures2, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2);
INIT_VK_STRUCT_S(VkImageCreateInfo, VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO);
INIT_VK_STRUCT_S(VkImageViewCreateInfo, VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO);
INIT_VK_STRUCT_S(VkBufferCreateInfo, VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO);
INIT_VK_STRUCT_S(VkCommandPoolCreateInfo, VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO);
INIT_VK_STRUCT_S(VkCommandBufferAllocateInfo, VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO);
INIT_VK_STRUCT_S(VkCopyBufferToImageInfo2, VK_STRUCTURE_TYPE_COPY_BUFFER_TO_IMAGE_INFO_2);
INIT_VK_STRUCT_S(VkBufferImageCopy2, VK_STRUCTURE_TYPE_BUFFER_IMAGE_COPY_2);
INIT_VK_STRUCT_S(VkImageMemoryBarrier2, VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2);
INIT_VK_STRUCT_S(VkDependencyInfo, VK_STRUCTURE_TYPE_DEPENDENCY_INFO);
INIT_VK_STRUCT_S(VkBlitImageInfo2, VK_STRUCTURE_TYPE_BLIT_IMAGE_INFO_2);
INIT_VK_STRUCT_S(VkCommandBufferBeginInfo, VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO);
INIT_VK_STRUCT_S(VkImageBlit2, VK_STRUCTURE_TYPE_IMAGE_BLIT_2);
INIT_VK_STRUCT_S(VkSubmitInfo2, VK_STRUCTURE_TYPE_SUBMIT_INFO_2);
INIT_VK_STRUCT_S(VkCommandBufferSubmitInfo, VK_STRUCTURE_TYPE_COMMAND_BUFFER_SUBMIT_INFO);
INIT_VK_STRUCT_S(VkBufferDeviceAddressInfo, VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO);
INIT_VK_STRUCT_S(VkAccelerationStructureGeometryKHR, VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_KHR);
INIT_VK_STRUCT_S(VkAccelerationStructureGeometryTrianglesDataKHR, VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_TRIANGLES_DATA_KHR);
INIT_VK_STRUCT_S(VkAccelerationStructureBuildGeometryInfoKHR, VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR);
INIT_VK_STRUCT_S(VkAccelerationStructureBuildSizesInfoKHR, VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_SIZES_INFO_KHR);
INIT_VK_STRUCT_S(VkAccelerationStructureCreateInfoKHR, VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_KHR);
INIT_VK_STRUCT_S(VkPhysicalDeviceBufferDeviceAddressFeatures, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceAccelerationStructureFeaturesKHR, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR);
INIT_VK_STRUCT_S(VkPhysicalDeviceRayTracingPipelineFeaturesKHR, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_FEATURES_KHR);
INIT_VK_STRUCT_S(VkShaderModuleCreateInfo, VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineShaderStageCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO);
INIT_VK_STRUCT_S(VkDescriptorPoolCreateInfo, VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO);
INIT_VK_STRUCT_S(VkDescriptorSetAllocateInfo, VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO);
INIT_VK_STRUCT_S(VkWriteDescriptorSetAccelerationStructureKHR, VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_KHR);
INIT_VK_STRUCT_S(VkWriteDescriptorSet, VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET);
INIT_VK_STRUCT_S(VkSwapchainCreateInfoKHR, VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR);
INIT_VK_STRUCT_S(VkSemaphoreCreateInfo, VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO);
INIT_VK_STRUCT_S(VkFenceCreateInfo, VK_STRUCTURE_TYPE_FENCE_CREATE_INFO);
INIT_VK_STRUCT_S(VkAcquireNextImageInfoKHR, VK_STRUCTURE_TYPE_ACQUIRE_NEXT_IMAGE_INFO_KHR);
INIT_VK_STRUCT_S(VkSemaphoreSubmitInfo, VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO);
INIT_VK_STRUCT_S(VkPresentInfoKHR, VK_STRUCTURE_TYPE_PRESENT_INFO_KHR);
INIT_VK_STRUCT_S(VkPhysicalDeviceRayTracingPipelinePropertiesKHR, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_TRACING_PIPELINE_PROPERTIES_KHR);
INIT_VK_STRUCT_S(VkPhysicalDeviceAccelerationStructurePropertiesKHR, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_PROPERTIES_KHR);
INIT_VK_STRUCT_S(VkDescriptorSetVariableDescriptorCountAllocateInfo, VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO);
INIT_VK_STRUCT_S(VkSamplerCreateInfo, VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO);
INIT_VK_STRUCT_S(VkDescriptorSetLayoutBindingFlagsCreateInfo, VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO);
INIT_VK_STRUCT_S(VkPhysicalDeviceScalarBlockLayoutFeatures, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceMaintenance5FeaturesKHR, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES_KHR);
INIT_VK_STRUCT_S(VkComputePipelineCreateInfo, VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineVertexInputStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineInputAssemblyStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineTessellationStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineViewportStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineRasterizationStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineMultisampleStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineDepthStencilStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineColorBlendStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineDynamicStateCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO);
INIT_VK_STRUCT_S(VkGraphicsPipelineCreateInfo, VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPipelineLayoutCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO);
INIT_VK_STRUCT_S(VkDescriptorSetLayoutCreateInfo, VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO);
INIT_VK_STRUCT_S(VkRayTracingPipelineCreateInfoKHR, VK_STRUCTURE_TYPE_RAY_TRACING_PIPELINE_CREATE_INFO_KHR);
INIT_VK_STRUCT_S(VkRayTracingShaderGroupCreateInfoKHR, VK_STRUCTURE_TYPE_RAY_TRACING_SHADER_GROUP_CREATE_INFO_KHR);
INIT_VK_STRUCT_S(VkPipelineRenderingCreateInfo, VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO);
INIT_VK_STRUCT_S(VkSemaphoreTypeCreateInfo, VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO);
INIT_VK_STRUCT_S(VkPhysicalDeviceVulkan12Features, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES);
INIT_VK_STRUCT_S(VkPhysicalDeviceRayQueryFeaturesKHR, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_QUERY_FEATURES_KHR);
INIT_VK_STRUCT_S(VkPhysicalDeviceProperties2, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2);
INIT_VK_STRUCT_S(VkRenderingAttachmentInfo, VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO);
INIT_VK_STRUCT_S(VkRenderingInfo, VK_STRUCTURE_TYPE_RENDERING_INFO);
INIT_VK_STRUCT_S(VkAccelerationStructureGeometryInstancesDataKHR, VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_INSTANCES_DATA_KHR);
INIT_VK_STRUCT_S(VkBufferMemoryBarrier2, VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2);
INIT_VK_STRUCT_S(VkCopyBufferInfo2, VK_STRUCTURE_TYPE_COPY_BUFFER_INFO_2);
INIT_VK_STRUCT_S(VkBufferCopy2, VK_STRUCTURE_TYPE_BUFFER_COPY_2);
INIT_VK_STRUCT_S(VkMemoryBarrier2, VK_STRUCTURE_TYPE_MEMORY_BARRIER_2);
INIT_VK_STRUCT_S(VkSamplerReductionModeCreateInfo, VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO);
INIT_VK_STRUCT_S(VkSemaphoreWaitInfo, VK_STRUCTURE_TYPE_SEMAPHORE_WAIT_INFO);
INIT_VK_STRUCT_S(VkSemaphoreSignalInfo, VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO);
INIT_VK_STRUCT_S(VkTimelineSemaphoreSubmitInfo, VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO);
INIT_VK_STRUCT_S(VkDebugUtilsLabelEXT, VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT);
INIT_VK_STRUCT_S(VkQueryPoolCreateInfo, VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO);
INIT_VK_STRUCT_S(VkMemoryRequirements2, VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2);
INIT_VK_STRUCT_S(VkImageMemoryRequirementsInfo2, VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2);
INIT_VK_STRUCT_S(VkBufferMemoryRequirementsInfo2, VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2);

#undef INIT_VK_STRUCT
#undef INIT_VK_STRUCT_S

}
}
}

// clang-format on